USE BANCO
GO

SET NOCOUNT ON

DECLARE @TIPO            AS VARCHAR(2)
DECLARE @PRODUTO         AS INT
DECLARE @CUSTO           AS VARCHAR(10)
DECLARE @QTDE_AJUSTE     AS INT
DECLARE @LOTE            AS VARCHAR(20)
DECLARE @DATA_VENCIMENTO AS DATETIME
DECLARE @DATA_FABRICACAO AS DATETIME
DECLARE @PISCOFINS       AS VARCHAR(1)
DECLARE @CODFILIAL       AS INT
DECLARE @CODFILIAL_AUX   AS INT
DECLARE @COMPETENCIA     AS VARCHAR(6)
DECLARE @SEQUENCIAL      AS NUMERIC(9)
DECLARE @GRUPO           AS INT
DECLARE @QTNOTASFILIAL   AS INT

DECLARE @CONTADOR        AS INT
DECLARE @CONT_GRUPO      AS INT
DECLARE @CONT_QTNOTAS    AS INT

DECLARE CURSOR_MONTA_GRUPOS CURSOR
	FOR SELECT
			 TIPO,
			 PRODUTO,
			 CUSTO,
			 QTDE_AJUSTE,
			 LOTE,
			 DATA_VENCIMENTO,
			 DATA_FABRICACAO,
			 PISCOFINS,
			 CODFILIAL,
			 COMPETENCIA,
			 SEQUENCIAL,
			 GRUPO,
			 QTNOTASFILIAL
	    FROM BANCO..TABELA WITH(NOLOCK)
	    ORDER BY CODFILIAL

OPEN CURSOR_MONTA_GRUPOS

-- INCREMENTA CURSOR
FETCH NEXT FROM CURSOR_MONTA_GRUPOS
INTO @TIPO, @PRODUTO, @CUSTO, @QTDE_AJUSTE, @LOTE, 
     @DATA_VENCIMENTO, @DATA_FABRICACAO, @PISCOFINS, 
	 @CODFILIAL, @COMPETENCIA, @SEQUENCIAL, @GRUPO, @QTNOTASFILIAL

WHILE @@FETCH_STATUS = 0
BEGIN
	
	SET @CODFILIAL_AUX = @CODFILIAL

	SET @CONTADOR = 1
    SET @CONT_GRUPO = 1
    SET @CONT_QTNOTAS = 1

	WHILE @@FETCH_STATUS = 0 AND @CODFILIAL_AUX = @CODFILIAL
	BEGIN

		IF @CONTADOR <= 250
		BEGIN
			-- MONTA OS GRUPOS DE NOTAS
			UPDATE FI
			SET   GRUPO = @CONT_GRUPO
			FROM  BANCO..TABELA FI
			WHERE PRODUTO = @PRODUTO
			AND   CODFILIAL = @CODFILIAL
		END

		IF @CONTADOR = 250
		BEGIN
			SET @CONTADOR = 0
			SET @CONT_GRUPO = @CONT_GRUPO + 1
			SET @CONT_QTNOTAS = @CONT_QTNOTAS + 1
		END

		-- UPDATE NA QUANTIDADE DE NOTAS
		UPDATE FI
		SET   QTNOTASFILIAL = @CONT_QTNOTAS
		FROM  BANCO..TABELA FI
		WHERE CODFILIAL = @CODFILIAL

		-- INCREMENTA CURSOR
		FETCH NEXT FROM CURSOR_MONTA_GRUPOS
		INTO @TIPO, @PRODUTO, @CUSTO, @QTDE_AJUSTE, @LOTE, 
			 @DATA_VENCIMENTO, @DATA_FABRICACAO, @PISCOFINS, 
			 @CODFILIAL, @COMPETENCIA, @SEQUENCIAL, @GRUPO, @QTNOTASFILIAL

		SET @CONTADOR = @CONTADOR + 1
	END

END

CLOSE CURSOR_MONTA_GRUPOS
DEALLOCATE CURSOR_MONTA_GRUPOS