USE NomeDoSeuBanco
GO

SET DATEFORMAT DMY
SET NOCOUNT ON

DECLARE @PERIODO_INI INT -- EX: 201802
DECLARE @PERIODO_FIM INT -- EX: 201803
DECLARE @PERIODO_AUX INT
DECLARE @FILIAL INT -- EX: 1

DECLARE @DATA_INI DATETIME
DECLARE @DATA_FIM DATETIME
DECLARE @NOMEBANCO VARCHAR(255)

SET @PERIODO_INI = 201701
SET @PERIODO_FIM = 201712
SET @PERIODO_AUX = @PERIODO_INI
SET @FILIAL = 1

WHILE @PERIODO_AUX <= @PERIODO_FIM
BEGIN

	SET @NOMEBANCO = 'NomeDoSeuBanco' + CONVERT(VARCHAR(6), @PERIODO_AUX)
	IF (SELECT COUNT(*) FROM MASTER..SYSDATABASES WHERE NAME = @NOMEBANCO) = 0
	BEGIN
		SET @NOMEBANCO = 'NomeDoSeuBanco'
	END

	SET @DATA_INI = '01/' + RIGHT(@PERIODO_AUX, 2) + '/' + LEFT(@PERIODO_AUX,4)
	SET @DATA_FIM = EOMONTH(@DATA_INI)

	SELECT @PERIODO_AUX AS PERIODO
	SELECT @DATA_INI AS DATA_INI, @DATA_FIM AS DATA_FIM
	SELECT @NOMEBANCO AS NOME_BANCO

	SET @PERIODO_AUX = (@PERIODO_AUX + 1) -- INCREMENTO PARA O PROX PERIODO
END
