USE Cosmos_v14b
GO

SET DATEFORMAT DMY
SET NOCOUNT ON

-- LÓGICA DE EXCLUSÃO DE TABELAS
IF EXISTS(SELECT 1 FROM TEMPDB..SYSOBJECTS WHERE ID = OBJECT_ID('TEMPDB..#TESTE_EXCLUSAO_TABELA'))
BEGIN
	DROP TABLE #TESTE_EXCLUSAO_TABELA
END

-- CRIAÇÃO DE TABELA TEMPORÁRIA
CREATE TABLE #TESTE_EXCLUSAO_TABELA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50),
	IDADE INT NOT NULL,
	RG VARCHAR(14) NOT NULL,
	CPF VARCHAR(11) NOT NULL
)

INSERT INTO #TESTE_EXCLUSAO_TABELA
SELECT 'SAMUEL CAMILO DOS SANTOS', 25, '2007738932-1', '12328852312'

--SELECT * FROM #TESTE_EXCLUSAO_TABELA WITH(NOLOCK)