USE <nomebanco>
GO

SET DATEFORMAT YMD

DECLARE @PERIODO_INICIAL VARCHAR(6) -- EX: 201312
DECLARE @PERIODO_FINAL   VARCHAR(6) -- EX: 201411
DECLARE @PERIODO_AUX     VARCHAR(6)
DECLARE @DATA_INI DATETIME
declare @estado varchar(2)

SET @PERIODO_INICIAL = '201401'
SET @PERIODO_FINAL   = '201412'
SET @PERIODO_AUX = @PERIODO_INICIAL

-- DEFINE O PRIMEIRO DIA DO MÊS
SET @DATA_INI = CONVERT(VARCHAR(6),LEFT(@PERIODO_INICIAL,4)) + '-' + CONVERT(VARCHAR(6),RIGHT(@PERIODO_INICIAL,2)) + '-' + '01'
--SET @DATA_FIM = EOMONTH(@DATA_INI)

WHILE @PERIODO_AUX <= @PERIODO_FINAL
BEGIN
    
	SELECT @PERIODO_AUX
	-- ADD UM MÊS
	SET @DATA_INI = DATEADD(MONTH, 1, @DATA_INI)
	-- RETORNA SOMENTE O PERIODO(MÊS/ANO) DO NOVO MÊS
    SET @PERIODO_AUX = CONVERT(VARCHAR(6), @DATA_INI, 112)
END