USE Cosmos_v14b
GO

SET DATEFORMAT DMY
SET NOCOUNT ON

DECLARE @PERIODO_INI INT -- EX: 201802
DECLARE @PERIODO_FIM INT -- EX: 201803
DECLARE @PERIODO_AUX INT
DECLARE @FILIAL INT -- EX: 1

DECLARE @DATA_INI DATETIME
DECLARE @DATA_FIM DATETIME

SET @PERIODO_INI = 201802
SET @PERIODO_FIM = 201810
SET @PERIODO_AUX = @PERIODO_INI
SET @FILIAL = 1

SET @DATA_INI = '01/' + RIGHT(@PERIODO_INI, 2) + '/' + LEFT(@PERIODO_INI,4)
SET @DATA_FIM = EOMONTH(@DATA_INI)

WHILE @PERIODO_AUX <= @PERIODO_FIM
BEGIN
	SELECT @PERIODO_AUX

	SET @DATA_INI = '01/' + RIGHT(@PERIODO_AUX, 2) + '/' + LEFT(@PERIODO_AUX,4)
	SET @DATA_FIM = EOMONTH(@DATA_INI)

	SELECT @DATA_INI, @DATA_FIM

	SET @PERIODO_AUX = (@PERIODO_AUX + 1)
END
